sudo: required

services:
  - docker

language: scala

scala:
  - 2.12.2

deploy:
  - provider: script
    script: scripts/docker.sh
    on:
      branch: master

  - provider: script
    script: scripts/docker.sh
    on:
      branch: dev
