sudo: required

services:
  - docker

language: scala

scala:
  - 2.12.2

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: scripts/docker.sh
    on:
      branch: master