sudo: required

services:
  - docker

language: scala

scala:
  - 2.12.2

env:
  - DATABASE_URL=dummy

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

deploy:
  - provider: script
    script: scripts/docker.sh
    on:
      branch: master

  - provider: script
    script: scripts/docker.sh
    on:
      branch: dev
