version: '3'

services:
  postgres:
    container_name: load-manager-db
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: load-manager
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux